version: '3.8'
services:
  frontend-dev:
    container_name: municipalidad-frontend-dev
    image: ${DOCKER_HUB_USERNAME}/${DOCKER_HUB_FRONTEND_IMAGE}:dev
    build:
      context: .
      target: development
    environment:
      - VITE_APP_API_URL=${VITE_APP_API_URL}
      - VITE_APP_API_URL=${VITE_APP_API_URL_DOCKER}
      - SERVER_ORIGIN=${SERVER_ORIGIN}
    ports:
      - "${FRONTEND_HOST_PORT}:${FRONTEND_CONTAINER_PORT}"
    expose:
      - ${FRONTEND_CONTAINER_PORT}
    volumes:
      - type: bind
        source: .
        target: /app
      - /app/node_modules
    command: npm run dev