version: '3.8'
services:
  frontend-prod:
    container_name: municipalidad-frontend-prod
    image: ${DOCKER_HUB_USERNAME}/${DOCKER_HUB_FRONTEND_IMAGE}:prod
    build:
      context: .
      target: production
    environment:
      - VITE_APP_API_URL=${VITE_APP_API_URL}
    ports:
      - "${FRONTEND_HOST_PORT}:${FRONTEND_CONTAINER_PORT}"
    expose:
      - 80
    command: nginx -g "daemon off;"
